version: '3'
services:
  kafka-0:
    image: vepo/kafka:3.7.0
    container_name: kafka-0
    ports:
     - 9092:9092
     - 9093:9093
    environment:
      KAFKA_CLUSTER_ID: N0UOwvnVR7ORiwq0M4do9w
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://kafka-0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0:9093,2@kafka-1:9095,3@kafka-2:9097
  kafka-1:
    image: vepo/kafka:3.7.0
    container_name: kafka-1
    ports:
     - 9094:9094
     - 9095:9095
    environment:
      KAFKA_CLUSTER_ID: N0UOwvnVR7ORiwq0M4do9w
      KAFKA_BROKER_ID: 2
      KAFKA_NODE_ID: 2
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_LISTENERS: PLAINTEXT://:9094,CONTROLLER://kafka-1:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0:9093,2@kafka-1:9095,3@kafka-2:9097
  kafka-2:
    image: vepo/kafka:3.7.0
    container_name: kafka-2
    ports:
     - 9096:9096
     - 9097:9097
    environment:
      KAFKA_CLUSTER_ID: N0UOwvnVR7ORiwq0M4do9w
      KAFKA_BROKER_ID: 3
      KAFKA_NODE_ID: 3
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_LISTENERS: PLAINTEXT://:9096,CONTROLLER://kafka-2:9097
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9096
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0:9093,2@kafka-1:9095,3@kafka-2:9097
  producer-1:
    image: jbangdev/jbang-action
    container_name: producer-1
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    volumes:
      - ./producer:/producer
    command: /producer/ProduceData.java
  consumer-1:
    image: jbangdev/jbang-action
    container_name: consumer-1
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    volumes:
      - ./consumer:/consumer
    command: /consumer/ConsumeData.java
  consumer-1:
    image: jbangdev/jbang-action
    container_name: consumer-1
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      GROUP_ID: main-group
    volumes:
      - ./consumer:/consumer
    command: /consumer/ConsumeData.java
  consumer-2:
    image: jbangdev/jbang-action
    container_name: consumer-2
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      GROUP_ID: main-group
    volumes:
      - ./consumer:/consumer
    command: /consumer/ConsumeData.java
  consumer-2-1:
    image: jbangdev/jbang-action
    container_name: consumer-21
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      GROUP_ID: secondary-group
    volumes:
      - ./consumer:/consumer
    command: /consumer/ConsumeData.java
  consumer-2-2:
    image: jbangdev/jbang-action
    container_name: consumer-22
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      GROUP_ID: secondary-group
    volumes:
      - ./consumer:/consumer
    command: /consumer/ConsumeData.java
  consumer-2-3:
    image: jbangdev/jbang-action
    container_name: consumer-23
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      GROUP_ID: secondary-group
    volumes:
      - ./consumer:/consumer
    command: /consumer/ConsumeData.java
  frontend:
    image: vepo/maestro-kafka-manager:0.0.2-SNAPSHOT
    container_name: frontend
    depends_on:
      - kafka-manager-db
    ports:
      - 8080:8080
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: kafka-manager
      QUARKUS_DATASOURCE_PASSWORD: kafka-manager
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://kafka-manager-db:5432/kafka-manager
      QUARKUS_DATASOURCE_JDBC_DRIVER: org.postgresql.Driver
  kafka-manager-db:
    image: postgres:13
    container_name: kafka-manager-db
    environment:
      POSTGRES_USER: kafka-manager
      POSTGRES_PASSWORD: kafka-manager
      POSTGRES_DB: kafka-manager