name: Docker Build

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Install all the dependencies
      run: mvn clean install
    - name: Build Production Delivery
      working-directory: ./maestro-kafka-manager
      run: mvn clean package -Pproduction
    - name: Build Docker image
      working-directory: ./maestro-kafka-manager
      run: "docker build -f src/main/docker/Dockerfile.jvm -t vepo/maestro-kafka-manager:${{ env.RELEASE_VERSION }} ."
    - name: Docker loging
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ vars.DOCKERHUB_USERNAME }} --password-stdin
    - name: Docker push
      run: docker push vepo/maestro-kafka-manager:${{ env.RELEASE_VERSION }}

